name: actionlint

on:
  pull_request:
    branches: [main]

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.changes.outputs.src }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            src:
              - '.github/workflows/*'

  actionlint-status:
    runs-on: ubuntu-latest
    needs:
      - actionlint
    permissions: {}
    if: failure()
    steps:
      - run: exit 1

  actionlint:
    needs: paths-filter
    if: needs.paths-filter.outputs.changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: actionlint
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
        shell: bash
