name: actionlint

on:
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/*"

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install actionlint
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash) 1.6.17
      - name: actionlint
        run: actionlint -color
