name: auto-assign

on:
  pull_request:

jobs:
  assign:
    name: Set assignees
    runs-on: ubuntu-latest
    steps:
      - name: Set assignees
        run: |
          assignee_count=$(cat "${{ github.event_path }}" | jq '.pull_request.assignees | length')
          echo "$assignee_count"
          if [[ "0" = "$assignee_count" ]]; then
            curl -X POST \
                 -H "Content-Type: application/json" \
                 -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -d "{ \"assignees\": [\"${{ github.actor }}\"] }" \
                 "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/assignees"
          fi
