name: branch-and-tag

on:
  push:
    tags:
      - v1.*

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: check
        run: |
          if [ ${{ startsWith( github.ref, 'refs/tags/' ) }} == 'true' ]; then
            echo 'tag'
          else
            echo 'push'
          fi
