name: branch-and-tag

on:
  push:
    branches:
      - '*'
    tags:
      - v1.*

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: check
        run: |
          if [ ${{ startsWith( github.ref, 'refs/tags/' ) }} == 'true' ]; then
            echo 'tag'
          else
            echo 'push'
          fi
      - name: get env
        env:
          TAG: ${{ github.event_name == 'push' && github.ref_name || github.event.number }} # REF_NAME is branch name or tag name for push
        run: |
          echo "$TAG"
