name: check-actions-name

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: for f in `ls .github/workflows/*yml`; do name=$(yq e '.name' $f); ls .github/workflows/${name}.yml; done
