name: check-actions-name

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - run: for f in .github/workflows/*yml; do name=$(yq e '.name' "$f"); ls ".github/workflows/${name}.yml"; done
