name: check-change

on: [pull_request]

jobs:
  check-change:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Pull Request Number
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "pr: $PR_NUMBER"
          echo "::set-env name=PR_NUMBER::$PR_NUMBER"
      # - name: Approve Pull Request
      #   uses: juliangruber/approve-pull-request-action@v1
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     number: ${{ env.PR_NUMBER }}
