name: cleanup-gha-cache
on:
  pull_request:
    types:
      - closed
  workflow_call:
jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Cleanup PR caches
        run: |
          REPO=${{ github.repository }}
          PR_REF="refs/pull/${{ github.event.pull_request.number }}/merge"

          echo "Fetching caches for PR #${{ github.event.pull_request.number }}"

          # キャッシュリストを取得し、各キャッシュIDを削除
          gh cache list \
            --repo "$REPO" \
            --ref "$PR_REF" \
            --limit 100 \
            --json id \
            --jq '.[].id' | \
          while IFS= read -r cache_id; do
            if [ -n "$cache_id" ]; then
              echo "Deleting cache ID: $cache_id"
              gh cache delete "$cache_id" --repo "$REPO"
            fi
          done

          echo "Cache cleanup completed for PR #${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
