name: create-pr-if-outdated

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

env:
  BRANCH_NAME: update-date-in-readme
  BASE_BRANCH_NAME: main

jobs:
  create-pr-if-outdated:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BASE_BRANCH_NAME }}

      - name: update date in readme
        run: |
          git_last_updated_date=$(git log -1 --format="%at" -- . ":(exclude)README.md" | xargs -I{} date -d @{} +%Y-%m-%d)
          echo "git_last_updated_date: $git_last_updated_date"
          sed -i "s/.*Last Updated: \(.*\)/- Last Updated: $git_last_updated_date/" README.md

      - name: check if need to commit
        id: need_commit
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "need_commit=true" >> "$GITHUB_OUTPUT"
          else
            echo "need_commit=false" >> "$GITHUB_OUTPUT"
          fi

      # GitHub Actions are NOT triggered in this PR
      - name: create-pull-request
        if: steps.need_commit.outputs.need_commit == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update updated_on (github token)'
          branch: update-updated-on-github-token
          title: 'chore: update updated_on (github token)'
          body: 'Update updated_on automatically (github token)'
          base: main
          delete-branch: true

  create-pr-with-github-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BASE_BRANCH_NAME }}

      - name: update date in readme
        run: |
          git_last_updated_date=$(git log -1 --format="%at" -- . ":(exclude)README.md" | xargs -I{} date -d @{} +%Y-%m-%d)
          echo "git_last_updated_date: $git_last_updated_date"
          sed -i "s/.*Last Updated: \(.*\)/- Last Updated: $git_last_updated_date/" README.md

      - name: check if need to commit
        id: need_commit
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "need_commit=true" >> "$GITHUB_OUTPUT"
          else
            echo "need_commit=false" >> "$GITHUB_OUTPUT"
          fi

      - name: create-github-app-token
        if: steps.need_commit.outputs.need_commit == 'true'
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_TEST_APP_ID }}
          private-key: ${{ secrets.GH_TEST_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      # GitHub Actions are triggered in this PR
      - name: create-pull-request
        if: steps.need_commit.outputs.need_commit == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: 'chore: update updated_on (github app)'
          branch: update-updated-on-github-app
          title: 'chore: update updated_on (github app)'
          body: 'Update updated_on automatically (github app)'
          base: main
          delete-branch: true
