name: create-pr-if-outdated

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

env:
  BRANCH_NAME: update-date-in-readme
  BASE_BRANCH_NAME: main

jobs:
  create-pr-if-outdated:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ env.BASE_BRANCH_NAME }}

      - name: update readme
        run: |
          git_last_updated_date=$(git log -1 --format="%at" -- . ":(exclude)README.md" | xargs -I{} date -d @{} +%Y-%m-%d)
          python_version=$(cat .python-version)
          echo "git_last_updated_date: $git_last_updated_date"
          sed -i "s/.*Last Updated: \(.*\)/- Last Updated: $git_last_updated_date/" README.md
          sed -i "s/.*Python Version: \(.*\)/- Python Version: $python_version/" README.md

      - name: check if need to commit
        id: need_commit
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "need_commit=true" >> "$GITHUB_OUTPUT"
          else
            echo "need_commit=false" >> "$GITHUB_OUTPUT"
          fi

      # GitHub Actions are NOT triggered in this PR
      - name: create-pull-request
        if: steps.need_commit.outputs.need_commit == 'true'
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update readme (github token)'
          branch: update-readme
          title: 'chore: update readme (github token)'
          body: 'Update readme automatically (github token)'
          base: main
          delete-branch: true

  create-pr-with-github-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ env.BASE_BRANCH_NAME }}

      - name: update readme
        run: |
          git_last_updated_date=$(git log -1 --format="%at" -- . ":(exclude)README.md" | xargs -I{} date -d @{} +%Y-%m-%d)
          python_version=$(cat .python-version)
          echo "git_last_updated_date: $git_last_updated_date"
          sed -i "s/.*Last Updated: \(.*\)/- Last Updated: $git_last_updated_date/" README.md
          sed -i "s/.*Python Version: \(.*\)/- Python Version: $python_version/" README.md

      - name: check if need to commit
        id: need_commit
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "need_commit=true" >> "$GITHUB_OUTPUT"
          else
            echo "need_commit=false" >> "$GITHUB_OUTPUT"
          fi

      - name: create-github-app-token
        if: steps.need_commit.outputs.need_commit == 'true'
        id: app-token
        uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1.11.6
        with:
          app-id: ${{ secrets.GH_TEST_APP_ID }}
          private-key: ${{ secrets.GH_TEST_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      # GitHub Actions are triggered in this PR
      - name: create-pull-request
        id: create-pull-request
        if: steps.need_commit.outputs.need_commit == 'true'
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: 'chore: update readme (github app)'
          branch: update-readme-github-app
          title: 'chore: update readme (github app)'
          body: 'Update readme automatically (github app)'
          base: main
          delete-branch: true

      - name: enable pr auto merge
        run: gh pr merge --squash --auto ${{ steps.create-pull-request.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
