name: create-pull-request

on:
  push:
    branches:
      - nakamasato-patch-2
      - main

jobs:
  create-pr-with-github-token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check and Update Date
        id: date_check
        run: |
          TODAY=$(date +"%Y-%m-%d")
          FILE_DATE=$(cat updated_on.txt || echo "")
          if [ "$FILE_DATE" != "$TODAY" ]; then
            echo "$TODAY" > updated_on.txt
            echo "updated=true" >> "$GITHUB_OUTPUT"
          else
            echo "updated=false" >> "$GITHUB_OUTPUT"
          fi

      # - name: Commit and Push Changes
      #   if: steps.date_check.outputs.updated == 'true'
      #   run: |
      #     git config --local user.name "github-actions[bot]"
      #     git config --local user.email "github-actions[bot]@users.noreply.github.com"
      #     git add updated_on.txt
      #     git commit -m "Update updated_on.txt with today's date"
      #     git push

      - name: create-pull-request
        if: steps.date_check.outputs.updated == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update updated_on (github token)'
          branch: update-updated-on-github-token
          title: 'chore: update updated_on (github token)'
          body: 'Update updated_on automatically (github token)'
          base: main
          delete-branch: true

  create-pr-with-github-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check and Update Date
        id: date_check
        run: |
          TODAY=$(date +"%Y-%m-%d")
          FILE_DATE=$(cat updated_on.txt || echo "")
          if [ "$FILE_DATE" != "$TODAY" ]; then
            echo "$TODAY" > updated_on.txt
            echo "updated=true" >> "$GITHUB_OUTPUT"
          else
            echo "updated=false" >> "$GITHUB_OUTPUT"
          fi

      - name: create-github-app-token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_TEST_APP_ID }}
          private-key: ${{ secrets.GH_TEST_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Commit and Push Changes
        if: steps.date_check.outputs.updated == 'true'
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add updated_on.txt
          git commit -m "Update updated_on.txt with today's date"
          git push origin update-updated-on-github-app

      - name: Create PR
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh pr create --base main --head update-updated-on-github-app --title "Test" --body "Test"

      # failed
      # - name: create-pull-request
      #   if: steps.date_check.outputs.updated == 'true'
      #   uses: peter-evans/create-pull-request@v5
      #   with:
      #     token: ${{ steps.app-token.outputs.token }}
      #     commit-message: 'chore: update updated_on (github app)'
      #     branch: update-updated-on-github-app
      #     title: 'chore: update updated_on (github app)'
      #     body: 'Update updated_on automatically (github app)'
      #     base: main
      #     delete-branch: true
