name: create-pr-if-outdated

on:
  push:
    branches:
      - master

jobs:
  create-pr-if-outdated:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: check date in readme
        id: check
        run: |
          last_updated_date=$(grep -i 'last updated' README.md | sed 's/.*Last Updated: \(.*\)/\1/')
          git_last_updated_date=$(git log -1 --format="%at" | xargs -I{} date -d @{} +%Y-%m-%d)
          echo "git_last_updated_date: $git_last_updated_date"
          if [ "$last_updated_date" = "$git_last_updated_date" ];then
            outdated=false
          else
            outdated=true
          fi
          echo "::set-output name=outdated::$outdated"
          echo "::set-output name=updated_date::$git_last_updated_date"

      - name: update date in readme and commit
        if:  ${{ steps.check.outputs.outdated == 'true' }}
        id: commit
        run: |
          sed -i "s/.*Last Updated: \(.*\)/- Last Updated: ${{ steps.check.outputs.updated_date }}/" README.md
          branch_name=update-date-in-readme
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b $branch_name
          git add .
          git commit -m 'update date'
          git push -u origin HEAD -f
          echo "::set-output name=branch_name::$branch_name"

      - name: Check if pr exists
        id: check_pr
        if:  ${{ steps.check.outputs.outdated == 'true' }}
        run: |
          pr_title="Update last updated date in README"
          base_branch="master"
          echo "::set-output name=count::$(gh pr list -S head:${{ steps.commit.outputs.branch_name }} -B $base_branch | wc -l)"
          echo "::set-output name=pr_title::$pr_title"
          echo "::set-output name=base_branch::$base_branch"

      - name: Create release pr
        if: ${{  steps.check.outputs.outdated == 'true' && steps.check_pr.outputs.count == 0 }}
        run: |
          gh pr create -B "${{ steps.check_pr.outputs.base_branch }}" -t "${{ steps.check_pr.outputs.pr_title }}" -b ""
