name: default-commands

on:
  pull_request:
    paths:
      - .github/workflows/default-commands.yml

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: zip
        run: |
          touch test.txt
          zip test.txt.zip test.txt

      - name: jq
        run: |
          echo '{"key": "value"}' | jq .

      - name: awscli
        run: aws --version

      - name: yq
        run: |
          echo 'key: value' | yq e '.key' -

      - name: cal
        run: cal $(date +"%m %Y") | awk 'NF {DAYS = $NF}; END {print DAYS}'

      - name: bc
        run: printf "%.2f" $(echo "scale=2;3/2" | bc)
