name: failure

on: pull_request

jobs:
  test1: # succeed
    runs-on: ubuntu-latest
    steps:
      - id: fail_step
        continue-on-error: true
        run: exit 1

      - run: echo ${{ steps.fail_step.outcome }}
      
      - if: failure() && steps.fail_step.outcome == 'failure'
        run: exit 1
