name: failure

on:
  pull_request:
    paths:
      - .github/workflows/failure.yml

jobs:
  just-fail:
    if: github.event.pull_request.draft == true
    runs-on: ubuntu-latest
    steps:
      - id: fail_step
        run: exit 1

      - run: echo ${{ steps.fail_step.outcome }} # not called

  fail-with-post-process:
    if: github.event.pull_request.draft == true
    runs-on: ubuntu-latest
    steps:
      - id: fail_step
        continue-on-error: true
        run: exit 1

      - name: post process regardless of sucess or failure
        run: echo ${{ steps.fail_step.outcome }} # failure

      - name: make it fail when the first step failed
        if: steps.fail_step.outcome == 'failure'
        run: exit 1

  succeed-with-post-process:
    if: github.event.pull_request.draft == true
    runs-on: ubuntu-latest
    steps:
      - id: succeed_step
        continue-on-error: true
        run: echo succeed

      - name: post process regardless of sucess or failure
        run: echo ${{ steps.succeed_step.outcome }} # success

      - name: make it fail when the first step failed
        if: steps.succeed_step.outcome == 'failure'
        run: exit 1

  fail-with-post-process-for-failure:
    if: github.event.pull_request.draft == true
    runs-on: ubuntu-latest
    steps:
      - id: fail_step
        run: exit 1

      - if: failure()
        name: post process only called when the first step fails
        run: echo ${{ steps.fail_step.outcome }} # failure

  succeed-with-post-process-for-failure:
    if: github.event.pull_request.draft == true
    runs-on: ubuntu-latest
    steps:
      - id: succeed_step
        run: echo succeed

      - if: failure()
        name: post process only called when the first step fails
        run: echo ${{ steps.succeed_step.outcome }}

  succeed:
    runs-on: ubuntu-latest
    steps:
      - id: suceed_step
        continue-on-error: true
        run: echo succeed

      - run: echo ${{ steps.suceed_step.outcome }} # success
