# https://zenn.dev/shunsuke_suzuki/articles/improve-cicd-with-github-comment
name: github-comment

on: pull_request

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: aquaproj/aqua-installer@baef45299b36669c0015d0d8bc630272c3493e78 # v2.3.1
        with:
          aqua_version: v2.17.0

      - run: github-comment hide
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Check github-comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "hello" | github-comment post -stdin-template
