# https://zenn.dev/shunsuke_suzuki/articles/improve-cicd-with-github-comment
name: github-comment

on: pull_request

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      - uses: aquaproj/aqua-installer@4551ec64e21bf0f557c2525135ff0bd2cba40ec7 # v3.0.0
        with:
          aqua_version: v2.17.0

      - run: github-comment hide
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Check github-comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "hello" | github-comment post -stdin-template
