# https://zenn.dev/shunsuke_suzuki/articles/improve-cicd-with-github-comment
name: github-comment

on: pull_request

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: v2.17.0

      - run: github-comment hide
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Check github-comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "hello" | github-comment post -stdin-template
