# https://zenn.dev/shunsuke_suzuki/articles/improve-cicd-with-github-comment
name: github-comment

on: pull_request

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: aquaproj/aqua-installer@5e54e5cee8a95ee2ce7c04cb993da6dfad13e59c # v3.1.2
        with:
          aqua_version: v2.17.0

      - run: github-comment hide
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Check github-comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "hello" | github-comment post -stdin-template
