# https://zenn.dev/shunsuke_suzuki/articles/improve-cicd-with-github-comment
name: github-comment

on: pull_request

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: aquaproj/aqua-installer@928a2ee4243a9ee8312d80dc8cbaca88fb602a91 # v2.2.0
        with:
          aqua_version: v2.17.0

      - run: github-comment hide
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Check github-comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "hello" | github-comment post -stdin-template
