name: graphviz

on:
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: install graphviz
        uses: ts-graphviz/setup-graphviz@v1
        with:
          ubuntu-skip-apt-update: 'false' # default false

      - name: check version
        run: dot -V
