name: graphviz

on:
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: install graphviz
        run: |
          apt-get update
          apt-get install -y graphviz
          dot -V
