name: graphviz

on:
  pull_request:

jobs:
  setup-graphviz:
    runs-on: ubuntu-latest
    steps:
      - name: install graphviz
        uses: ts-graphviz/setup-graphviz@v2
        with:
          ubuntu-skip-apt-update: 'false' # default false

      - name: check version
        run: dot -V
  install:
    runs-on: ubuntu-latest
    steps:
      - name: install graphviz
        run: |
          curl -o graphviz.deb https://gitlab.com/api/v4/projects/4207231/packages/generic/graphviz-releases/9.0.0/ubuntu_20.04_graphviz-9.0.0-cmake.deb
          sudo dpkg -i graphviz.deb
          sudo apt-get install -f

      - name: check version
        run: dot -V
