name: keep-only-one-comment-on-pr

on: pull_request

permissions:
  pull-requests: write # to enable dependabot to write comment

env:
  COMMENT_BODY_IDENTIFIER: test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Find Comment
        uses: peter-evans/find-comment@3eae4d37986fb5a8592848f6a574fdf654e61f9e # v3.1.0
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          body-includes: ${{ env.COMMENT_BODY_IDENTIFIER }}

      - name: Delete comment
        if: ${{ steps.fc.outputs.comment-id != 0 }}
        uses: jungwinter/comment@fda92dbcb5e7e79cccd55ecb107a8a3d7802a469 # v1.1.0
        with:
          type: delete
          comment_id: ${{ steps.fc.outputs.comment-id }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `<!-- ${process.env.COMMENT_BODY_IDENTIFIER} -->\nAdd \`release\` label if you want to release when this pull request is merged. (${new Date()}) [keep-only-one-comment-on-pr.yml](${{ github.server_url }}/${{ github.repository }}/blob/main/.github/workflows/keep-only-one-comment-on-pr.yml)`
            })
