name: llm-pr-reviewer

on:
  pull_request:
    branches: [ main ]

jobs:
  test-action:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nakamasato/github-actions/llm-pr-reviewer@llm-pr-reviewer
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
