name: matrix-from-previous-job-output-3
on:
  pull_request:
  push:
    paths:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.set-matrix.outputs.env }}
    steps:
      - id: set-matrix
        run: |
          if [[ "${{ github.event_name }}" = "pull_request" ]]; then
            echo "env=[\"dev\"]" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" = "push" ]]; then
            echo "env=[\"dev\", \"prod\"]" >> $GITHUB_OUTPUT
          fi

  execute:
    strategy:
      matrix:
        matrix: ${{ fromJson(needs.setup.outputs.env) }}
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - run: |
          echo "matrix: ${{ matrix.matrix }}"
