name: matrix-from-previous-job-output-3
on:
  pull_request:
  push:

jobs:
  # From https://github.com/dorny/paths-filter
  # JOB to run change detection
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      # Expose matched filters as job 'app' output variable
      app: ${{ steps.filter.outputs.changes }}
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          github-actions:
            - '.github/workflows/**'
          poetry:
            - 'poetry/**'
    - name: set matrix
      id: set-matrix
      run: |
        echo "matrix=[\"pull_request1\", \"pull_request2\"]" >> "$GITHUB_OUTPUT"

  execute:
    strategy:
      matrix:
        app: ${{ fromJson(needs.set-matrix.outputs.app) }}
        matrix: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
    runs-on: ubuntu-latest
    needs: [set-matrix]
    steps:
      - name: "app: ${{ matrix.app }}, matrix: ${{ matrix.matrix }}"
        run: |
          echo "app: ${{ matrix.app }}, matrix: ${{ matrix.matrix }}"
