name: matrix-from-previous-job-output
on:
  pull_request:
  push:
    paths:
      - .github/workflows/matrix-from-previous-job.yml
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.pull-request.outputs.matrix }} || ${{ steps.push.outputs.matrix }}
    steps:
      - id: pull-request
        if: github.event_name == 'pull_request'
        run: echo "::set-output name=matrix::[\"pull_request1\", \"pull_request2\"]"
      - id: push
        if: github.event_name == 'push'
        run: echo "::set-output name=matrix::[\"push1\", \"push2\"]"
  execute:
    strategy:
      matrix:
        matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - run: |
          echo "matrix: ${{ matrix.matrix }}"
