name: matrix-from-previous-job-output-2
on:
  pull_request:

jobs:
  # setup:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     matrix: ${{ steps.outputs.matrix }}
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

  #     - name: get all changes
  #       id: changed-files-yaml
  #       uses: tj-actions/changed-files@v38
  #       with:
  #         files_yaml: |
  #           dev:
  #             - 'static/dev/**'
  #           prod:
  #             - 'static/prod/**'

  #     - name: make matrix
  #       id: matrix
  #       run: |
  #         echo "matrix=[{\"env\": \"dev\", \"changed\": \"${{ steps.changed-files-yaml.outputs.test_any_changed }}\" }, {}]' >> $GITHUB_OUTPUT

  execute:
    strategy:
      matrix:
        # matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
        env: ["dev", "prod"]
        include:
          - env: "dev"
            changed: true
          - env: "prod"
            changed: false
    runs-on: ubuntu-latest
    # needs: [setup]
    steps:
      - run: |
          echo "env: ${{ matrix.env }}, changed: ${{ matrix.changed }}"
