name: matrix-from-previous-job-output
on:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - id: generate-matrix
        run: echo "::set-output name=matrix::[\"item1\", \"item2\"]"
  execute:
    strategy:
      matrix:
        matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - run: |
          echo "matrix: ${{ matrix.matrix }}"
