name: matrix-from-previous-job-output
on:
  pull_request:
  push:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          if [[ "${{ github.event_name }}" = "pull_request" ]]; then
            echo "matrix=[\"pull_request1\", \"pull_request2\"]" >> "$GITHUB_OUTPUT"
          elif [[ "${{ github.event_name }}" = "push" ]]; then
            echo "matrix=[\"push1\", \"push2\"]" >> "$GITHUB_OUTPUT"
          fi
  execute:
    strategy:
      matrix:
        matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - run: |
          echo "matrix: ${{ matrix.matrix }}"

  setup-simple:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix-pull-request.outputs.matrix || steps.set-matrix-push.outputs.matrix }} # use pull-request if exists, otherwise use push
    steps:
      - name: set matrix for pull_request
        id: set-matrix-pull-request
        if: github.event_name == 'pull_request'
        run: echo "matrix=[\"pull_request1\", \"pull_request2\"]" >> "$GITHUB_OUTPUT"

      - name: set matrix for push
        id: set-matrix-push
        if: github.event_name == 'push'
        run: echo "matrix=[\"push1\", \"push2\"]" >> "$GITHUB_OUTPUT"

  execute-simple:
    strategy:
      matrix:
        matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
    runs-on: ubuntu-latest
    needs: [setup-simple]
    steps:
      - run: |
          echo "matrix: ${{ matrix.matrix }}"
