name: matrix-from-previous-job-output-3

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # From https://github.com/dorny/paths-filter
  # JOB to run change detection
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      include: ${{ steps.set-matrix.outputs.include }}
    steps:
    - uses: actions/checkout@v4
    # Deploy each app to dev for pull request
    # Deploy each app to both prod and dev for push (main)
    - name: set matrix
      id: set-matrix
      run: |
        if [[ "${{ github.event_name }}" = "pull_request" ]]; then
          echo "include=[{\"app\": \"app1\", \"env\": \"dev\"}, {\"app\": \"app2\", \"env\": \"dev\"}]"  >> "$GITHUB_OUTPUT"
        elif [[ "${{ github.event_name }}" = "push" ]]; then
          echo "include=[{\"app\": \"app1\", \"env\": \"dev\"}, {\"app\": \"app1\", \"env\": \"prod\"}, {\"app\": \"app2\", \"env\": \"dev\"}, {\"app\": \"app2\", \"env\": \"prod\"}]"  >> "$GITHUB_OUTPUT"
        fi

  execute:
    strategy:
      matrix:
        include: ${{ fromJson(needs.set-matrix.outputs.include) }}
    runs-on: ubuntu-latest
    needs: [set-matrix]
    steps:
      - name: "app: ${{ matrix.app }}, matrix: ${{ matrix.env }}"
        run: |
          echo "app: ${{ matrix.app }}, matrix: ${{ matrix.env }}"
