name: matrix-from-previous-job-output-3
on:
  pull_request:
  push:
    paths:
      - main

# jobs:
#   setup:
#     runs-on: ubuntu-latest
#     outputs:
#       env: ${{ steps.set-matrix.outputs.env }}
#     steps:
#       - id: set-matrix
#         run: |
#           if [[ "${{ github.event_name }}" = "pull_request" ]]; then
#             echo "env=[\"dev\"]" >> $GITHUB_OUTPUT
#           elif [[ "${{ github.event_name }}" = "push" ]]; then
#             echo "env=[\"dev\", \"prod\"]" >> $GITHUB_OUTPUT
#           fi

env:
  ENVS: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && '["dev", "prod"]' || '["dev"]' }}

jobs:
  execute:
    strategy:
      matrix:
        env: ${{ fromJson($ENVS) }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "matrix: ${{ matrix.env }}"
