name: matrix-from-previous-job-output-4

on:
  pull_request:
    paths:
      - .github/workflows/matrix-from-previous-job-output-4.yml
      - schemas/**.json
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the workflow'
        type: choice
        required: true
        default: 'dev'
        options:
          - 'dev'
          - 'prod'
      dataset:
        description: 'Dataset to sync'
        type: choice
        required: true
        options:
          - 'dataset1'
          - 'dataset2'
      table:
        description: 'Table to sync'
        type: choice
        required: true
        options:
          - 'table1'
          - 'table2'

  # this is used in dbt-test.yaml
  workflow_call:
    inputs:
      environment:
        description: 'Environment to run the workflow (dev)'
        type: string
        default: 'dev'
      dataset:
        description: 'Dataset to sync'
        type: string
        required: true
      table:
        description: 'Table to sync'
        type: string
        required: true
      schemafile:
        description: 'Schema file to sync (optional) default is schemas/<dataset>/<table>.json'
        type: string
        required: true

concurrency:
  group: table-sync-${{ github.ref }}-${{ inputs.dataset }}-${{ inputs.table }}
  cancel-in-progress: true

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      CHANGED_SCHEMA_FILES: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Get changed schema files
        if: ${{ github.event_name == 'pull_request' }}
        id: changed-schema-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            schemas/**.json
          matrix: true
      - id: set-matrix
        run: |
          if [[ "${{ github.event_name }}" = "pull_request" ]]; then
            echo "matrix=${{ steps.changed-files.outputs.all_changed_files }}" >> "$GITHUB_OUTPUT"
          elif [[ "${{ github.event_name }}" = "workflow_dispatch" ]]; then
            echo "matrix=[\"schemas/${{ inputs.dataset }}/${{ inputs.table }}.json\"]" >> "$GITHUB_OUTPUT"
          elif [[ "${{ github.event_name }}" = "workflow_call" ]]; then
            echo "matrix=[\"${{ inputs.schemafile }}\"]" >> "$GITHUB_OUTPUT"
          fi

  update:
    needs: [set-matrix]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        schemafile: ${{ fromJson(needs.set-matrix.outputs.CHANGED_SCHEMA_FILES) }}
    steps:
      - name: ${{ matrix.schemafile }}
        run: echo ${{ matrix.schemafile }}
