name: matrix-from-previous-job-output
on:
  pull_request:
  push:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        if: github.event_name == 'pull_request'
        run: 
          if [[ "${{ github.event_name }}" = "pull_request" ]]; then
            echo "::set-output name=matrix::[\"pull_request1\", \"pull_request2\"]"
          elif [[ "${{ github.event_name }}" = "push" ]]; then
            echo "::set-output name=matrix::[\"push1\", \"push2\"]"
          fi
  execute:
    strategy:
      matrix:
        matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - run: |
          echo "matrix: ${{ matrix.matrix }}"
