name: pip-cache

on:
  push:
    paths:
      - python-script/requirements.txt
      - .github/workflows/pip-cache.yml

jobs:
  with-cache:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version-file: .python-version

      # https://github.com/actions/cache/blob/master/examples.md#python---pip
      - name: pip cache restore
        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        id: pip-cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('python-script/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: pip install
        if: steps.pip-cache.outputs.cache-hit != 'true'
        run: pip install -r python-script/requirements.txt

      - name: pip cache save
        uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        if: github.ref_name == 'main'
        with:
          path: ~/.cache/pip
          key: ${{ steps.pip-cache.outputs.cache-primary-key }}

  no-cache:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version-file: .python-version

      - name: pip install
        run: pip install -r python-script/requirements.txt
