name: pip-cache

on:
  push:
    paths:
      - python-script/requirements.txt
      - .github/workflows/pip-cache.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      # https://github.com/actions/cache/blob/master/examples.md#python---pip
      - name: pip cache
        uses: actions/cache@v4
        id: pip-cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('python-script/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: pip install
        if: steps.pip-cache.outputs.cache-hit != 'true'
        run: pip install -r python-script/requirements.txt
