name: cache-pip

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('python-script/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Check cache hit
        if: steps.pip-cache.outputs.cache-hit != 'true'
        run: pip install -r python-script/requirements.txt
