name: prereleased

on:
  release:
    types: [prereleased]

jobs:
  preleased:
    if: github.event.release.target_commitish == 'main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: deploy
      run: |
        echo "preleased"
