name: prereleased

on:
  release:
    types: [prereleased]

jobs:
  preleased:
    if: github.event.release.target_commitish == 'main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - name: deploy
      run: |
        echo "preleased"
