name: prereleased

on:
  release:
    types: [prereleased]

jobs:
  preleased:
    if: github.event.release.target_commitish == 'main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
    - name: deploy
      run: |
        echo "preleased"
