name: prereleased

on:
  release:
    types: [prereleased]

jobs:
  preleased:
    if: github.event.release.target_commitish == 'main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
    - name: deploy
      run: |
        echo "preleased"
