name: prereleased

on:
  release:
    types: [prereleased]

jobs:
  preleased:
    if: github.event.release.target_commitish == 'main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
    - name: deploy
      run: |
        echo "preleased"
