name: pull-request-types
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  pull-requests: write

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: echo ${{ github.event.pull_request.type }}
        run: |
          echo "${{ github.event.pull_request.type }}"
