name: pull-request-label
on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Show removed label
        run: |
          echo "${{ github.event.action }} label: ${{ github.event.label.name }}"
          echo "all labels attached to pr: ${{ toJson(github.event.pull_request.labels.*.name) }}"
          echo "Full payload:"
          echo '${{ toJson(github.event) }}'
