name: pull-request-title-starts-with

on:
  pull_request:

jobs:
  check:
    if: "startsWith(${{ github.event.pull_request.title }}, 'fix(deps): update dependency langchain to')"
    runs-on: ubuntu-latest
    steps:
      - run: echo "run"
