name: pull-request-title-starts-with

on:
  pull_request:

jobs:
  skip-langchain-update:
    if: "! startsWith(github.event.pull_request.title, 'fix(deps): update dependency langchain to')"
    runs-on: ubuntu-latest
    steps:
      - run: echo "not updating langchain"

  langchain-update:
    if: "startsWith(github.event.pull_request.title, 'fix(deps): update dependency langchain to')"
    runs-on: ubuntu-latest
    steps:
      - run: echo "update langchain"
