name: push-commit-with-github-app

on:
  pull_request:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check and Update Date
        id: date_check
        run: |
          TODAY=$(date +"%Y-%m-%d")
          FILE_DATE=$(cat updated_on.txt || echo "")
          if [ "$FILE_DATE" != "$TODAY" ]; then
            echo "$TODAY" > updated_on.txt
            echo "updated=true" >> $GITHUB_ENV
          else
            echo "updated=false" >> $GITHUB_ENV
          fi

      - name: Commit and Push Changes
        if: env.updated == 'true'
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add updated_on.txt
          git commit -m "Update updated_on.txt with today's date"
          git push
