name: shellcheck

on:
  pull_request:
    paths:
      - '**.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: changed shell scripts
        id: changed-files
        uses: tj-actions/changed-files@48d8f15b2aaa3d255ca5af3eba4870f807ce6b3c # v45.0.2
        with:
          files_yaml: |
            shell:
              - '**.sh'

      - name: run shellcheck for all changed shell scripts
        if: steps.changed-files.outputs.shell_any_changed == 'true'
        run: |
          # https://github.com/rhysd/actionlint/issues/355
          # shellcheck disable=SC2043
          for file in ${{ steps.changed-files.outputs.shell_all_changed_files }}; do
            echo "$file was changed"
            shellcheck "$file"
          done
