name: shellcheck

on:
  pull_request:
    paths:
      - '**.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: changed shell scripts
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          files_yaml: |
            shell:
              - '**.sh'

      - name: run shellcheck for all changed shell scripts
        if: steps.changed-files.outputs.shell_any_changed == 'true'
        run: |
          for file in "${{ steps.changed-files.outputs.shell_all_changed_files }}"; do
            echo "$file was changed"
            shellcheck "$file"
          done
