name: update-pull-request-body
on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: update pull request body
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          pr_number: 316
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          debug: true
          script: |
            contentToAdd = "new"

            console.log(contentToAdd);

            const pull = await github.rest.issues.get({
              issue_number: process.env.pr_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            console.log(pull.data.body);

            github.rest.issues.update({
              issue_number: process.env.pr_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${pull.data.body}\n- #${context.issue.number}`
            });
