name: update-pull-request-body
on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      - name: update pull request body
        uses: actions/github-script@v7
        env:
          pr_number: 316
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          debug: true
          script: |
            contentToAdd = "new"

            console.log(contentToAdd);

            const pull = await github.rest.issues.get({
              issue_number: process.env.pr_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            console.log(pull.data.body);

            github.rest.issues.update({
              issue_number: process.env.pr_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${pull.data.body}\n- #${context.issue.number}`
            });
