name: workflow-dispatch

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      environment:
        description: 'Environment (either development or production)'
        type: environment
        required: true
        default: development
        options:
        - production
        - development
jobs:
  print-inputs:
    uses: nakamasato/github-actions-practice/.github/workflows/print-workflow-dispatch-inputs.yaml@main
    with:
      environment: ${{ inputs.environment }}
      logLevel: ${{ inputs.logLevel }}
  run:
    needs: [print-inputs]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: echo running
