name: workflow-dispatch-with-environment

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  print-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: job summary
        run: |
          echo "### inputs" >> $GITHUB_STEP_SUMMARY
          echo "- logLevel: ${{ inputs.logLevel }}" >> $GITHUB_STEP_SUMMARY
  run:
    needs: [print-inputs]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo ${{ inputs.logLevel }}
