name: workflow-dispatch

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      environment:
        description: 'Environment (either development or production)'
        type: environment
        required: true
        default: development
jobs:
  print-inputs-from-remote-workflow:
    uses: nakamasato/github-actions-practice/.github/workflows/print-workflow-dispatch-inputs.yaml@main
    with:
      environment: ${{ inputs.environment }}
      logLevel: ${{ inputs.logLevel }}
  run:
    needs: [print-inputs-from-remote-workflow]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: echo running

  print-inputs:
    needs: [print-inputs-from-remote-workflow]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: |
          echo "### condition" >> "$GITHUB_STEP_SUMMARY"
          echo "- branch: ${{ github.ref_name }}" >> "$GITHUB_STEP_SUMMARY"
