name: zip

on:
  pull_request:
    paths:
      - .github/workflows/zip.yml

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - name: zip
        run: |
          touch test.txt
          zip test.txt.zip test.txt
